name: Check

on:
  push:
    branches:
      - master

env:
  HUSKY: 0

jobs:
  check:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure NPM authentication token for GitHub Packages
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.FINANDO_GITHUB_BOT_TOKEN }}

      - name: Install dependencies
        run: npm ci --quiet --ignore-scripts

      - name: Audit dependencies
        run: npm audit --omit=dev --audit-level=moderate

      - name: Lint project
        run: npm run lint:project

      - name: Test
        run: npm run test:coverage
